import PolicyPage from '@/components/PolicyPage'; import { createPageMetadata } from '@/lib/seo';
export const metadata = createPageMetadata({ title: 'Commission terms', description: 'Review the commercial decisions and terms to confirm before commissioning an artwork from Oma Achebe.', pathname: '/commission-terms' });
export default function CommissionTermsPage() {
  return <PolicyPage label="Policy" title="Commission terms" intro="The working terms for a commissioned artwork by Oma Achebe." sections={[
    { heading: 'Brief and quote', body: ['A commission begins with a written brief covering the subject, size, medium, palette, intended setting, deadline, delivery location, and any reference material. Artsy by Oma will then provide a quote and proposed schedule.', 'The commission is accepted when the client confirms the written scope and pays the deposit. Requests outside the agreed scope may require a revised quote or schedule.'] },
    { heading: 'Deposit and balance', body: 'A 50% deposit is due to reserve production time and purchase commission-specific materials. The remaining 50% is due before dispatch, collection, or installation. Work and delivery dates are not reserved until the deposit clears.' },
    { heading: 'Process and approvals', body: ['The artist may share progress images or a sketch where helpful. The client receives up to two reasonable revision rounds during the agreed approval stage. Changes after approval, or changes that materially alter the brief, may carry an additional fee and extend the schedule.', 'Artistic decisions about composition, texture, colour variation, and finish remain with the artist unless the written brief states otherwise.'] },
    { heading: 'Timeline and delivery', body: ['The written quote includes an estimated completion window. The schedule may move if feedback, approvals, reference files, payment, material availability, or delivery details are delayed.', 'Delivery, collection, framing, installation, and insurance are quoted separately where applicable. The client is responsible for ensuring that the delivery location is ready and suitable for the artwork.'] },
    { heading: 'Cancellation', body: ['The client may request cancellation in writing. The deposit covers time reserved, planning, materials, and work already completed and is normally non-refundable, except where Artsy by Oma agrees otherwise or applicable law requires a different result.', 'If the artist must cancel before completion, we will discuss a reasonable transfer, replacement plan, or refund of the unused portion of the fee.'] },
    { heading: 'Ownership and copyright', body: ['Ownership of the physical artwork transfers after the full balance has cleared. Copyright and moral rights remain with Oma Achebe unless a separate written assignment says otherwise.', 'The artist may photograph and show completed work for portfolio, website, editorial, and social media purposes unless the client requests confidentiality in writing before completion. The client may display the physical artwork but may not reproduce, resell, or license the image for commercial use without written permission.'] },
    { heading: 'Care and remedies', body: 'The client should follow any care instructions supplied with the artwork and contact the studio promptly about a material defect or damage. Nothing in these terms removes a consumer right that cannot lawfully be excluded under Nigerian law.' },
  ]} />;
}
