import PolicyPage from '@/components/PolicyPage'; import { createPageMetadata } from '@/lib/seo';
export const metadata = createPageMetadata({ title: 'Privacy', description: 'Read how Artsy by Oma handles information shared through the website, enquiries, accounts, and purchases.', pathname: '/privacy' });
export default function PrivacyPage() {
  return <PolicyPage label="Policy" title="Privacy" intro="How Artsy by Oma handles information shared through the website, studio bookings, enquiries, and purchases." sections={[
    { heading: 'Who this notice is for', body: ['This notice applies to visitors, customers, account holders, booking guests, commission clients, and anyone who contacts Artsy by Oma through the website or our published contact channels.', 'Artsy by Oma is operated by Oma Achebe in Awka, Anambra, Nigeria. For privacy questions, contact support@artsybyoma.com.'] },
    { heading: 'Information we collect', body: ['We may collect your name, email address, phone number, delivery or billing details, booking preferences, commission brief, messages, and the information you choose to place in an account or enquiry form.', 'When you browse or use the site, we may receive device, browser, approximate location, log, and cookie information needed for security, performance, analytics, and remembering preferences. Payment details are handled by the payment provider; Artsy by Oma does not intentionally store full card numbers.'] },
    { heading: 'How we use information', body: ['We use information to answer enquiries, create and manage accounts, confirm and host experiences, process artwork orders, arrange delivery, provide customer support, send service messages, prevent fraud, improve the website, and keep business records.', 'We send marketing messages only where permitted and with a clear way to opt out. We do not sell personal information.'] },
    { heading: 'Service providers and sharing', body: ['We share only what is needed with service providers that help us run the website and fulfil your request, such as hosting, Firebase, payment processing, email delivery, analytics, and delivery partners. Those providers may process information on our instructions or under their own published terms.', 'We may disclose information where required by law, to protect the studio and its customers, or as part of a business transfer.'] },
    { heading: 'Retention and security', body: ['We keep enquiry and account information only as long as it is reasonably needed for the purpose collected, ongoing customer support, dispute handling, and legal or accounting requirements. We review stored information periodically and remove or anonymise what we no longer need.', 'We use reasonable administrative, technical, and organisational safeguards. No online service is completely risk-free, so please use a unique password and tell us promptly if you suspect unauthorised access.'] },
    { heading: 'Your choices and rights', body: ['You may ask us to access, correct, update, delete, or provide a copy of personal information we hold about you. You may also object to certain processing, withdraw consent where processing relies on consent, or ask us to limit processing where applicable.', 'To make a request, email support@artsybyoma.com with enough detail for us to identify the relevant records. We may need to verify your identity before responding. We aim to respond within a reasonable period and will explain if a legal exception applies.'] },
    { heading: 'Cookies and children', body: ['The site may use essential cookies and similar technologies for login, cart, security, and preferences, plus optional analytics where enabled. You can control non-essential cookies through your browser settings.', 'The website is intended for adults and families using the studio with a responsible adult. We do not knowingly request children’s personal information for independent accounts or marketing.'] },
    { heading: 'Changes to this notice', body: 'We may update this notice when our services, providers, or legal obligations change. The date at the top of this page shows when the current version took effect.' },
  ]} />;
}
