import PolicyPage from '@/components/PolicyPage'; import { createPageMetadata } from '@/lib/seo';
export const metadata = createPageMetadata({ title: 'Terms', description: 'Review the terms for using Artsy by Oma services, artwork enquiries, studio bookings, and purchases.', pathname: '/terms' });
export default function TermsPage() {
  return <PolicyPage label="Policy" title="Terms" intro="The terms that govern use of Artsy by Oma services, artwork purchases, commissions, and studio experiences." sections={[
    { heading: 'Using this website', body: ['By using artsybyoma.com, you agree to use it lawfully and respectfully. Website copy, images, artwork listings, logos, and other content belong to Artsy by Oma or the relevant rights holder and may not be copied, sold, or reused commercially without permission.', 'We may update listings, prices, availability, and these terms as the studio changes. The version posted on this page applies to a purchase, booking, or enquiry made after it is published.'] },
    { heading: 'Accounts and enquiries', body: ['You are responsible for giving accurate contact, booking, and delivery information and for keeping account credentials private. Tell us promptly if you believe an account has been used without permission.', 'An enquiry or request is not accepted until Artsy by Oma confirms it in writing. We may decline a request where availability, safety, legality, or the requested use is not suitable for the studio.'] },
    { heading: 'Artwork, products, and payment', body: ['Original artworks and creative products are handmade or individually selected. Small differences in colour, texture, finish, and dimensions may occur. We aim to describe each item accurately and will tell you when an item is unavailable or made to order.', 'Prices are shown in Nigerian naira unless stated otherwise. Payment must clear before an order is prepared or a booking is confirmed. Taxes, delivery fees, and any applicable third-party charges are shown or explained before payment.'] },
    { heading: 'Experiences and private events', body: ['Bookings are subject to the date, group size, activity, venue capacity, and payment terms shown at confirmation. Guests should arrive on time, follow studio instructions, and take reasonable care around paint, tools, furniture, equipment, and other guests.', 'For a private event, the organiser is responsible for sharing accurate group information and ensuring minors attend with an appropriate responsible adult. We may pause or end a session where conduct creates a safety risk or materially disrupts the studio.'] },
    { heading: 'Commissions', body: 'Commissioned work is governed by the written brief, quote, deposit, approval stages, delivery plan, and the Commission Terms page. A commission is not scheduled until the required deposit has cleared and the scope has been accepted in writing.' },
    { heading: 'Cancellations, returns, and delivery', body: 'Our current procedures for booking changes, returns, refunds, and delivery are set out on the Returns and refunds and Shipping and delivery pages. Nothing in these terms removes a consumer right that cannot lawfully be excluded.' },
    { heading: 'Responsibility and events outside our control', body: ['We take reasonable care in providing the site, products, and experiences, but we cannot promise that the website will always be uninterrupted or error-free. To the extent allowed by law, Artsy by Oma is not responsible for indirect loss, loss of opportunity, or events outside our reasonable control.', 'Nothing in these terms limits liability for fraud, death or personal injury caused by negligence, or any other liability that cannot legally be limited.'] },
    { heading: 'Law and contact', body: 'These terms are governed by the laws of Nigeria. If a concern cannot be resolved through support@artsybyoma.com, the parties may use any dispute-resolution or court process available under applicable Nigerian law.' },
  ]} />;
}
