import type { Metadata } from 'next';
import Link from 'next/link';
import Footer from '@/components/Footer';
import { SITE } from '@/lib/site';
import { createPageMetadata } from '@/lib/seo';

export const metadata: Metadata = createPageMetadata({ title: 'Commissions', description: 'Request a contemporary artwork commission from Oma Achebe for a home, hospitality space, gift, or collaboration.', pathname: '/art/commissions', image: '/images/selected-works/IMG_8055.jpg', imageAlt: 'Contemporary artwork by Oma Achebe' });

export default function CommissionsPage() { return <main id="main-content" className="site-main"><div className="page-shell"><header className="page-intro"><p className="eyebrow">Commissions</p><h1>A piece made for your space.</h1><p>Oma Achebe accepts a limited number of commissions for homes, hospitality spaces, gifting, and aligned collaborations. Share the feeling, scale, and context you have in mind.</p><Link href="/contact?subject=Commission%20enquiry" className="button button--primary mt-6">Start a commission enquiry</Link></header><div className="grid gap-10 md:grid-cols-3"><article className="content-section"><p className="eyebrow">01 · Brief</p><h2>Tell us the story.</h2><p className="mt-3 text-[var(--text-muted)] leading-relaxed">Share your space, preferred dimensions, palette, budget range, and the feeling you want the piece to carry.</p></article><article className="content-section"><p className="eyebrow">02 · Direction</p><h2>Shape the work.</h2><p className="mt-3 text-[var(--text-muted)] leading-relaxed">The studio confirms fit, timing, materials, and the next steps before any work begins.</p></article><article className="content-section"><p className="eyebrow">03 · Delivery</p><h2>Bring it home.</h2><p className="mt-3 text-[var(--text-muted)] leading-relaxed">Shipping, pickup, installation, framing, and certificate details are agreed in writing for each project.</p></article></div><p className="mt-16 text-sm text-[var(--text-muted)]">Based in {SITE.location}. Commission availability changes through the year.</p></div><Footer /></main>; }
