import PolicyPage from '@/components/PolicyPage'; import { createPageMetadata } from '@/lib/seo';
export const metadata = createPageMetadata({ title: 'Shipping and delivery', description: 'Learn how original artworks move from the Artsy by Oma studio in Awka to their new home.', pathname: '/shipping' });
export default function ShippingPage() {
  return <PolicyPage label="Policy" title="Shipping and delivery" intro="How original works and creative products move from the studio in Awka to their new home." sections={[
    { heading: 'Where we deliver', body: ['We arrange delivery within Nigeria and can discuss international delivery by written quote. The available method, estimated timing, delivery fee, and any import or customs charges are confirmed before an order is paid.', 'Collection from the Awka studio may be available by appointment. Exact directions are shared with confirmed customers and booking guests.'] },
    { heading: 'Processing times', body: ['Ready-to-ship items usually leave the studio within 3–10 business days after payment clears. Made-to-order and commissioned pieces follow the schedule in the written quote or commission agreement.', 'Delivery estimates are provided in good faith and can change because of carrier delays, public holidays, weather, customs, or other events outside the studio’s control.'] },
    { heading: 'Packaging and delivery', body: ['We package artworks and creative products with materials appropriate to their size, surface, and fragility. Delivery fees are paid by the customer unless a written quote says otherwise.', 'Please provide a complete address, a reachable phone number, and any delivery instructions. If a carrier cannot deliver because the address or recipient information is incomplete, additional delivery charges may apply.'] },
    { heading: 'Checking your order', body: ['Please inspect the package as soon as it arrives. If it appears damaged, photograph the outer packaging and the item before moving or repairing it, then contact support@artsybyoma.com within 48 hours so we can help with the carrier claim and next step.', 'If an item is materially not as described or arrives faulty, the Returns and refunds policy explains the available remedy.'] },
    { heading: 'International orders', body: 'The customer is responsible for providing accurate customs information and paying import duties, taxes, or clearance charges imposed by the destination country unless the written delivery quote expressly says otherwise.' },
  ]} />;
}
