import PolicyPage from '@/components/PolicyPage'; import { createPageMetadata } from '@/lib/seo';
export const metadata = createPageMetadata({ title: 'Returns and refunds', description: 'Review the Artsy by Oma approach to artwork returns, booking changes, refunds, and payment issues.', pathname: '/returns' });
export default function ReturnsPage() {
  return <PolicyPage label="Policy" title="Returns and refunds" intro="How Artsy by Oma handles artwork returns, booking changes, damaged deliveries, and payment issues." sections={[
    { heading: 'If an item is damaged or not as described', body: ['Please contact support@artsybyoma.com as soon as possible, ideally within 48 hours of delivery, with your order details and clear photographs. We may ask you to keep the packaging while we assess the issue.', 'Where an item is faulty, damaged in transit, or materially not as described, we will work with you on an appropriate repair, replacement, return, or refund. The remedy depends on the item and the circumstances and is subject to rights that apply under Nigerian consumer law.'] },
    { heading: 'Change-of-mind returns', body: ['For ready-made, unused items that are not personalised, contact us within 7 days of delivery to request a return. The item must be safely packaged and returned in its original condition. Return delivery is normally the customer’s responsibility unless the item is faulty or not as described.', 'Commissioned, personalised, altered, digital, or made-to-order items cannot normally be returned for a change of mind because they were created for a specific brief. This does not affect a remedy for a defect or material failure to match the agreed brief.'] },
    { heading: 'Bookings and private events', body: ['If you need to change or cancel an experience or private event, contact us at least 72 hours before the confirmed start time. We will normally offer one reschedule or a studio credit, subject to availability. A shorter-notice cancellation may attract a reasonable preparation or administration charge.', 'If Artsy by Oma must cancel or cannot provide the confirmed experience, we will offer a reschedule or refund for the affected booking.'] },
    { heading: 'Refund timing', body: 'Once a refund is approved, we aim to initiate it within 7 business days using the original payment method where possible. Bank or payment-provider processing times may take longer. Payment failures are not treated as completed orders or confirmed bookings until payment is verified.' },
    { heading: 'Questions and escalation', body: 'Start with support@artsybyoma.com and include your order or booking reference. We will review the details and explain the next step. Nothing on this page removes a consumer right that cannot lawfully be excluded.' },
  ]} />;
}
